/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.telas;

import java.sql.*;
import br.com.projeto.dal.ModuloConexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class TelaAvaliarMusicas extends javax.swing.JFrame {

    private String nomeUsuario;
    private int idUsuario;
    private double posto;
    private double somaDeNotas;
    private int qtdAvaliacoes;
    private int idMusica;
    
    Connection conexao = null;
    PreparedStatement pst, ps = null;
    ResultSet rs, rst= null;
    
    /**
     * @return the nomeUsuario
     */
    public String getNomeUsuario() {
        return nomeUsuario;
    }

    /**
     * @param nomeUsuario the nomeUsuario to set
     */
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    /**
     * @return the idUsuario
     */
    public int getIdUsuario() {
        return idUsuario;
    }

    /**
     * @param idUsuario the idUsuario to set
     */
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    /**
     * Creates new form TelaAvaliarMusicas
     */
    public TelaAvaliarMusicas() {
        initComponents();
        conexao = ModuloConexao.conector();
        setaNomeUsuario();
        setaIdUsuario();
        carregaMusicas();
    }

      private void setaIdUsuario(){
        String query = "select id_usuario from tbusuarios where nome_usuario = ?";
        try {
            pst = conexao.prepareStatement(query);
            pst.setString(1, getNomeUsuario());
            rs = pst.executeQuery();
            if(rs.next()){
                this.idUsuario = rs.getInt(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar Id do usuário.");
        }
    }
    
    private void setaNomeUsuario(){
        String query = "select nome_usuario from usuarioAtual";
        try {
            pst = conexao.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                this.nomeUsuario = rs.getString(1);
            }else{
                System.out.println("Não encontrei");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NotaGroup = new javax.swing.ButtonGroup();
        btnVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbNomeMusica = new javax.swing.JLabel();
        lbAutorMusica = new javax.swing.JLabel();
        btnConfirmarNota = new javax.swing.JButton();
        um = new javax.swing.JRadioButton();
        dois = new javax.swing.JRadioButton();
        tres = new javax.swing.JRadioButton();
        quatro = new javax.swing.JRadioButton();
        cinco = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliar Músicas"));

        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Música", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMusicas);
        if (tblMusicas.getColumnModel().getColumnCount() > 0) {
            tblMusicas.getColumnModel().getColumn(0).setResizable(false);
            tblMusicas.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Música Selecionada"));

        lbNomeMusica.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAutorMusica.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnConfirmarNota.setText("Confirmar Nota");
        btnConfirmarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarNotaActionPerformed(evt);
            }
        });

        NotaGroup.add(um);
        um.setText("1");

        NotaGroup.add(dois);
        dois.setText("2");

        NotaGroup.add(tres);
        tres.setText("3");

        NotaGroup.add(quatro);
        quatro.setText("4");

        NotaGroup.add(cinco);
        cinco.setText("5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sua Nota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNomeMusica, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(lbAutorMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnConfirmarNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(um)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tres)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cinco)
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbNomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(um)
                            .addComponent(dois)
                            .addComponent(tres)
                            .addComponent(quatro)
                            .addComponent(cinco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAutorMusica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarNota, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVoltar)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipal tela_principal = new TelaPrincipal();
        tela_principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tblMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusicasMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblMusicas.getModel();
        int linha = tblMusicas.getSelectedRow();
        lbNomeMusica.setText((String) tblMusicas.getValueAt(linha, 0));
        lbAutorMusica.setText((String) tblMusicas.getValueAt(linha, 1));
    }//GEN-LAST:event_tblMusicasMouseClicked

    private void btnConfirmarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarNotaActionPerformed
        cadastrarMusicaNoBanco();
    }//GEN-LAST:event_btnConfirmarNotaActionPerformed

    private void inicializaPosto(){
         String query = "select id_musica,posto, qtd_avaliacoes, soma_avaliacoes from tbmusicas where nome_musica = ? and nome_autor = ?";
         try {
            pst = conexao.prepareStatement(query);
            pst.setString(1,lbNomeMusica.getText());
            pst.setString(2,lbAutorMusica.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                this.idMusica = rs.getInt(1);
                this.posto = rs.getDouble(2);
                this.qtdAvaliacoes = rs.getInt(3);
                this.somaDeNotas = rs.getDouble(4);
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e); 
        }
    }
    
    private void cadastraPosto(){
         String query = "update tbmusicas set posto = ?, qtd_avaliacoes = ?, soma_avaliacoes = ? where id_musica = ?";
         try {
             String p = String.valueOf(this.posto);
             String qtd = String.valueOf(this.qtdAvaliacoes);
             String soma = String.valueOf(this.somaDeNotas);
             String id = String.valueOf(this.idMusica);
             pst = conexao.prepareStatement(query);
             pst.setString(1,p);
             pst.setString(2,qtd);
             pst.setString(3,soma);
             pst.setString(4,id);
             pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }
    
    private void desvinculaUsuarioMusica(){
        String query = "delete from usuarioXmusica where id_musica = ?";
        try {
            String id = String.valueOf(this.idMusica);
            pst = conexao.prepareStatement(query);
            pst.setString(1,id);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }
    
    
    private void cadastrarMusicaNoBanco(){
    // System.out.println(NotaGroup.getSelection().toString());
    int nota = 0;
       if(um.isSelected()){
           nota = 1;
       }else if(dois.isSelected()){
           nota = 2;
       }else if(tres.isSelected()){
           nota = 3;
       }else if(quatro.isSelected()){
           nota = 4;
       }else{
           nota = 5;
       }
       if(nota != 0){
          inicializaPosto();
          this.qtdAvaliacoes += 1;
          this.somaDeNotas += (double)nota;
          this.posto = this.somaDeNotas/this.qtdAvaliacoes;
          cadastraPosto();
          desvinculaUsuarioMusica();
          carregaMusicas();
          lbNomeMusica.setText("");
          lbAutorMusica.setText("");
       }
    }
    
    
    private void carregaMusicas(){
       DefaultTableModel model = (DefaultTableModel)tblMusicas.getModel();
       model.setRowCount(0);
       
       String query = "select id_musica from usuarioXmusica where nome_usuario = ?";
       try {
            pst = conexao.prepareStatement(query);
            pst.setString(1, this.getNomeUsuario());
            rs = pst.executeQuery();
            while(rs.next()){
                query = "select nome_musica,nome_autor from tbmusicas where id_musica = ?";
                ps = conexao.prepareStatement(query);
                ps.setString(1, rs.getString(1));
                rst = ps.executeQuery();
                if(rst.next()){
                    model.addRow(new Object[]{
                    rst.getString(1),
                    rst.getString(2)
                    });
                }
            }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Erro ao carregar músicas para o programa");
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAvaliarMusicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NotaGroup;
    private javax.swing.JButton btnConfirmarNota;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JRadioButton cinco;
    private javax.swing.JRadioButton dois;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAutorMusica;
    private javax.swing.JLabel lbNomeMusica;
    private javax.swing.JRadioButton quatro;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JRadioButton tres;
    private javax.swing.JRadioButton um;
    // End of variables declaration//GEN-END:variables
}
